# Generated by Django 4.1.1 on 2022-10-03 22:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Usuário')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Endereço de e-mail')),
                ('name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de início')),
                ('is_staff', models.BooleanField(default=False, verbose_name='É funcionário')),
                ('is_active', models.BooleanField(default=False, verbose_name='Está ativo')),
                ('role', models.CharField(max_length=255, verbose_name='Cargo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Usuários',
            },
        ),
    ]
