# Generated by Django 4.1.2 on 2022-10-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradmin',
            name='role',
        ),
        migrations.AlterField(
            model_name='useradmin',
            name='is_active',
            field=models.BooleanField(default=False, help_text='O usuário estará ativo para acessar o dashboard e o site administrativo', verbose_name='Está ativo'),
        ),
        migrations.AlterField(
            model_name='useradmin',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='O usuário estará habilitado para acessar o site administrativo', verbose_name='É funcionário'),
        ),
    ]
